config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check
  root to: 'home#index'

  resources :home do
    resources :tasks, only: [:show, :new, :create]
  end
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
# == Schema Information
#
# Table name: boards
#
#  id          :bigint           not null, primary key
#  description :text
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint           not null
#
# Indexes
#
#  index_boards_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Board < ApplicationRecord
  belongs_to :user

  has_many :tasks, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id          :bigint           not null, primary key
#  description :text
#  end_date    :datetime
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  board_id    :bigint           not null
#  user_id     :bigint           not null
#
# Indexes
#
#  index_tasks_on_board_id  (board_id)
#  index_tasks_on_user_id   (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Task < ApplicationRecord
  has_one_attached :eyecatch

  belongs_to :user
  belongs_to :board

  validates :title, presence: true
  validates :description, presence: true
  validates :end_date, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :boards, dependent: :destroy
  has_many :tasks, dependent: :destroy

  has_one_attached :avatar

  def avatar_image
    if avatar&.attached?
      avatar
    else
      'Users.png'
    end
  end

  def has_written?(board)
    boards.exists?(id: board.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :registration_permitted_parameters, if: :devise_controller?

  private
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:account_update, keys: %i(avatar))
    end

    def registration_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: %i(avatar))
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @boards = Board.all
  end

  def new
    @board = current_user.boards.build
  end

  def show
    @board = Board.find(params[:id])
    @tasks = @board.tasks
  end

  def create
    @board = current_user.boards.build(board_params)
    if @board.save
      redirect_to root_path, notice: '保存できました'
    else
      flash.now[:error] = '保存に失敗しました'
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @board = current_user.boards.find(params[:id])
  end

  def update
    @board = current_user.boards.find(params[:id])
    if @board.update(board_params)
      redirect_to root_path(@board), notice: '更新できました'
    else
      flash.now[:error] = '更新できませんでした'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    board = current_user.boards.find(params[:id])
    board.destroy!
    redirect_to root_path, notice: '削除に成功しました'
  end

  private
  def board_params
    params.require(:board).permit(:title, :description)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def show
  end

  def new
    board = Board.find(params[:home_id])
    @task = board.tasks.build
  end

  def create
    board = Board.find(params[:home_id])
    @task = board.tasks.build(task_params)
    @task.user = current_user
    if @task.save
      redirect_to home_path(board), notice: '保存できました'
    else
      flash.now[:error] = '保存に失敗しました'
      render :new, status: :unprocessable_entity
    end
  end

  private
  def task_params
    params.require(:task).permit(:title, :description, :end_date, :eyecatch)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/edit.html.haml
.container
  %ul
    - @board.errors.full_messages.each do |message|
      %li= message
  %h2 Edit Board
  = form_with(model: @board, url: home_path(@board), method: 'put', local: true) do |f|
    %div
      = f.label :title, 'Name'
    %div
      = f.text_field :title, class: 'text'
    %dev
      = f.label :description, 'Description'
    %div
      = f.text_area :description
    %div
      = f.submit 'Update', class: 'btn-primary'

app/views/home/index.html.haml
.container 
  %h2 All Boards
  - @boards.each do |board|
    = link_to home_path(board) do
      .board 
        .board_content 
          %h3.board_title 
            = board.title
          .board_description 
            = board.description
          .board_detail 
            = image_tag board.user.avatar_image, class: 'icon'
          - if user_signed_in? && current_user.has_written?(board)
            .board_detail_actions 
              .dropdown
                = image_tag 'Combined Shape.png', class: 'dropbtn'
                .dropdown-content.mini
                  = link_to 'Edit', edit_home_path(board)
                  = link_to 'Delete', home_path(board), data: { turbo_method: 'delete', turbo_confirm: '本当に削除してもよろしいですか？' }
  .board_new
    = link_to new_home_path do
      %p + Add new board

app/views/home/new.html.haml
.container
  %ul
    - @board.errors.full_messages.each do |message|
      %li= message
  %h2 New Board
  = form_with(model: @board, url: home_index_path, method: 'post', local: true) do |f|
    %div
      = f.label :title, 'Name'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :description, 'Description'
    %div
      = f.text_area :description
    %div
      = f.submit 'Save', class: 'btn-primary'

app/views/home/show.html.haml
.container 
  %h2
    = @board.title
  - @tasks.each do |task|
    .card 
      - if task.eyecatch.attached?
        .card_image 
          = image_tag task.eyecatch
      .card_content 
        %h3.card_title 
          = task.title
          .card_end_date 
            %p 期限
            = I18n.l(task.end_date, format: :default)
        .card_description 
          = task.description
        .card_detail 
          = image_tag task.user.avatar_image, class: 'icon'
          .card_comment
            %span= 23
            = image_tag 'comment-icon.png', class: 'comment-icon'

  .card_new
    = link_to new_home_task_path(@board) do
      %p + Add new card

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title TodoApp
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag "application", "data-turbo-track": "reload"
    = javascript_importmap_tags
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
  %body
    %header.header
      %p.header_pageTitle 
        = link_to 'Boards', root_path
      - if user_signed_in?
        .dropdown 
          = image_tag current_user.avatar_image, class: 'header_avatar dropbtn'
          .dropdown-content 
            = link_to 'Account', edit_user_registration_path
            = link_to 'Sign out', destroy_user_session_path, data: { turbo_method: 'delete' }
      - else
        = link_to 'Sign in', new_user_session_path, class: 'header_loginBtn'
    - if flash.present?
      .flash 
        - flash.each do |key, value|
          %div{:class => key}= value
    = yield

app/views/tasks/new.html.haml
.container
  %ul
    - @task.errors.full_messages.each do |message|
      %li= message
  %h2 New Card
  = form_with(model: @task, url: home_tasks_path(@task.board), local: true) do |f|
    %div
      = f.label :eyecatch, 'Eyecatch'
    %div
      = f.file_field :eyecatch, class: 'eyecatch'
    %div
      = f.label :title, 'Name'
    %div
      = f.text_field :title, class: 'text'
    %div
      = f.label :description, 'Description'
    %div
      = f.text_area :description
    %div
      = f.label :end_date, 'Deadline'
    %div
      = f.datetime_select :end_date
    %div
      = f.submit 'Save', class: 'btn-primary'